### ISSUE TITLE
Improve support for strings

### ISSUE THREAD

**Issue by anderslanglands** [vfx-rs/cppmm#11]
Currently cppmm attempts to be clever and replace string parameters with char* and handle copying into and out of std::string in the wrapper function.

I'm thinking now that this is not a great idea after all as it forces a lot of potentially unneccesary copying, and it makes things like handling vectors of strings (a common type in some APIs) hard to handle nicely. 

A better solution might be to create a dedicated opaquebytes wrapper type (std_string) that can be passed around through the API and which the caller is responsible for copying into and out of when they wish.

**Comment by luke-titley** [comment]
I agree with the last option. This is the same as std::vector I think and other types. A general solution for std::string and std::vector might be the way to go...

**Comment by anderslanglands** [comment]
Yep this is the way I'm leaning too, and smart pointers (and containers of smart pointers) will want to go this way as well

**Comment by luke-titley** [comment]
I don't mind looking at this.

**Comment by anderslanglands** [comment]
Great. I’ll assign this issue to you then. I’ll write up some pointers when I get a minute later today as you’ll need to do a bit of surgery to override the current string handling and make a base for other similar hard-codes types we’ll want to add later

**Comment by anderslanglands** [comment]
Heeey sorry for the delay.

So the main thing right now is that any type called "basic_string" is specially handled and either:
1) Converted into a (const) char* if it's a parameter : https://github.com/vfx-rs/cppmm/blob/7eaff89c2fa9b0d038f540fc9981b58b5d248166/src/type.cpp#L72
2) If it's a return type, then the function/method is transformed such that it instead returns an int representing the length of the copied string and two out parameters (mutable char* and int buffer size) are added to the parameter list to hold the copied string:  https://github.com/vfx-rs/cppmm/blob/7eaff89c2fa9b0d038f540fc9981b58b5d248166/src/function.cpp#L53
and then there's special handling in generating the definiton to use those transformed parameters: https://github.com/vfx-rs/cppmm/blob/7eaff89c2fa9b0d038f540fc9981b58b5d248166/src/function.cpp#L110

There's already a placeholder for string in TypeVariant: https://github.com/vfx-rs/cppmm/blob/7eaff89c2fa9b0d038f540fc9981b58b5d248166/src/type.hpp#L22 and then you just need to handle it as an opaquebytes type in Function::get_definition().

Let me know if that's enough to get going on and if you find anything else horribly stupid in there while you're digging.

**Comment by luke-titley** [comment]
Hey. Sorry for the radio silence. Have been fairly busy. Will pick this up over the weekend.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by luke-titley** [comment]
Just digging through here a bit more. What about string_view? You want me to change that as part of this work ?

**Comment by anderslanglands** [comment]
Potentially yeah. I don’t know if I’ve ever seen one returned anywhere, and
if not then it’s safe just to treat it as a char*, but for the sake of
future-proofing it’s probably worth handling it properly.

**Comment by luke-titley** [comment]
k. Most of the work so far has just been deleting code :). I'm guessing we're going to have a hard coded string opaquebytes string included in the output headers, everywhere.

**Comment by anderslanglands** [comment]
Yes I think so. We could have it try and figure out which source files need
to include the string headers similar to how it handles includes and casts
macros, but I figured that was a lot of extra complexity for very little
benefit so easier to #include “std_string.hpp” or whatever everywhere and
be done with it.

**Comment by luke-titley** [comment]
Hey.
So passing by reference and returning by value has been fairly straight forward, but I'm not clear about how you handle returning a reference to an opaquebytes type, I haven't spotted any:
```
if(.. is_ref) {
}
```
code anywhere for the standard opaquebytes path. I don't suppose you could point out roughly where it is?

**Comment by anderslanglands** [comment]
Huh, guess I never needed that yet for any of the test cases. I'd probably do it by adding another handler function similar to `get_opaquebytes_body`, e.g. `get_opaquebytes_ref_body`:
```c++
{c_type}* c_returns_ob_ref() {
    return to_c(&cpp:returns_ob_ref());
}
```

**Comment by luke-titley** [comment]
Not ready to be merged yet, but progress can be tracked here.
https://github.com/vfx-rs/cppmm/pull/15

**Comment by luke-titley** [comment]
Hey. So  I *think* most of the work is done. I'm able to round trip std::ffi::CStr into a std_string, then into a test test class, and back out into a std_string and CStr.

This is passing...

```rust
fn it_works() {
    let s = std::ffi::CString::new("this_is_a_test_string").unwrap();
    unsafe {
        let mut std_str = std_string::new();
        std_string_from_cstr(& mut std_str, s.as_ptr());

        // Check that the contents of the std_string is correct
        assert_eq!(std::ffi::CStr::from_ptr(std_string_c_str(&std_str)),
                   s.as_c_str());

        let t = test_Test_Test(&std_str);

        assert_eq!(std::ffi::CStr::from_ptr(std_string_c_str(test_Test_get_value(t))),
                   s.as_c_str());
    }
}
```

Methods + constructors seem fine. Need to copy/paste the work over to functions.

@anderslanglands, I think now might be a good time to get your eyes on the pull request.
Generated example is here: test/std/test-rust-sys

I have to say.. it feels a bit hacky writing special case code everywhere for std::string. Now that I understand the code more, I feel like I could have injected a record into the records vector and let the standard code paths generate it...

**Comment by anderslanglands** [comment]
You mean manually creating and injecting the appropriate Record on startup?
Yes that’s a much better idea! I’ll take a look at the PR later today but
yeah, that seems like a smarter approach, particularly as the list of
“special” types will balloon quickly.

**Comment by luke-titley** [comment]
Yes, I mean that.

**Comment by anderslanglands** [comment]
So my plan when I get time over the Christmas break is to merge this, write some more tests involving use of strings against different libraries, then refactor to do the record injection method you suggested. 

I’m happy to do this work unless this is something you would like to do?

**Comment by luke-titley** [comment]
okay great. No it's fine, you do it. I'm pretty swamped at the moment. You'll get it done quicker.

**Comment by anderslanglands** [comment]
Closed as no longer an issue with new architecture
