### ISSUE TITLE
Return wrapped type by reference produces incorrect implementation code

### ISSUE THREAD

**Issue by luke-titley** [vfx-rs/cppmm#18]
This is the c++ class method.

```
const TfToken & UsdPrim::GetTypeName() const;
```

this is the cppmm c wrapping implementation.. I'm removing the namespaces for legibility.
```
const pxr___TfToken* pxr___UsdPrim_GetTypeName(const pxr___UsdPrim* self) {
    pxr__::TfToken tmp = to_cpp(self)->GetTypeName();
    pxr___TfToken ret;
    new (&ret) pxr__::TfToken(std::move(tmp));
    return ret;
}
```

this obviously doesn't work, i'd expect something more like this, as we're returning by reference and TfToken is opaque, it should cast directly.

```
const pxr___TfToken* pxr___UsdPrim_GetTypeName(const pxr___UsdPrim* self) {
    return &to_cpp(to_cpp(self)->GetTypeName());
}
```

**Comment by anderslanglands** [comment]
Yep there are a couple of places where generation for opaque refs are broken like this. I'll take a look later.

**Comment by luke-titley** [comment]
If it's any use.
https://github.com/luke-titley/usd-sys

**Comment by luke-titley** [comment]
N/A
