### ISSUE TITLE
What version of c++ should we use for cppmm?

### ISSUE THREAD

**Issue by luke-titley** [vfx-rs/cppmm#22]
c++17 would be great, but I know the more recent you go the less likely old linux distros will be able to build it.
Are we sticking to c++11 and just finding backport headers for additional things we want ?

**Comment by anderslanglands** [comment]
I think we should peg ourselves one year behind the VFX reference platform.
So c++14 this year, c++17 next year.

**Comment by luke-titley** [comment]
c++14 is the answer
