### ISSUE TITLE
Define IO structure between astgen and asttoc

### ISSUE THREAD

**Issue by anderslanglands** [vfx-rs/cppmm#31]
I propose that cppmm as a whole works on the concept of a "binding project" as a way of organizing all the pieces. This would have the following structure:
```
project
    |------ project-ast
    |------ project-c
    |------ project-sys
```

`-ast` would contain the json ast, `-c` the generated C bindings and `-sys` the rust ffi bindings. In this model, one would pass `--output project` to astgen, which would create the `project` and `project-ast` directories and output the ast json files into `project-ast`. Then running `asttoc --input project` would find the json in `project-ast`, create `project-c` (and `project-sys` eventually) and write its output there.

Would probably be worth supporting `--output-ast-dir` in astgen (and on the other side `--input-ast-dir` in asttoc) to override the default behaviour if people wanted.

**Comment by anderslanglands** [comment]
Actually what makes more sense is for astgen/toc to specify the leaf directories explicitly, and have the project structure dictated by some future supervisor script that would run both of them with knowledge of the full project structure

**Comment by anderslanglands** [comment]
OK this is now set up so that asttoc takes a required positional parameter which is the input path, and an optional "-o" parameter specifying the output path, and the tests are updated to use this and diff against both the json ast and the C output

**Comment by luke-titley** [comment]
I've just spotted this. It's much better.

**Comment by anderslanglands** [comment]
Closing as this was done a while ago
