### ISSUE TITLE
Support for "throws" attribute for exception handling

### ISSUE THREAD

**Issue by anderslanglands** [vfx-rs/cppmm#43]
I'm adding a new CPPMM_THROWS attribute to astgen:
```c++
#define CPPMM_THROWS(x) __attribute__((annotate("cppmm:throws:" #x)))
```

The idea being we provide a list here of what exceptions the function might throw so that the asttoc can write out exception handling machinery. This means we probably want to change the separator in all attributes from a colon to e.g. a pipe:
```c++
"cppmm:throws:Iex::LogicExc" // hmm
"cppmm|throws|Iex::LogicExc" // easier?
```

Which then leaves the question of how we want to handle multiple exception types and what to do about them in the C layer. The first thing that springs to mind is to do something like this:

```c++
void Foo::foo(int a, int b) CPPMM_THROWS(Iex::ArgExc[1] Iex::LogicExc[2] Iex::BaseExc[3] std::exception[4]) 
// becomes:
threadlocal std::string cppmm_tl_exc_what;
int Foo_foo(int a, int b) {
    try {
        Foo::foo(a, b);
    } except (const Iex::ArgExc& e) {
        cppmm_tl_exc_what = e.what();
        return 1;
    } except (const Iex::LogicExc& e) {
        cppmm_tl_exc_what = e.what();
        return 2;
     } except (const Iex::BaseExc& e) {
        cppmm_tl_exc_what = e.what();
        return 3;
     } except (const std::exception& e) {
        cppmm_tl_exc_what = e.what();
        return 4;
    }
}
```
We could also replace those integer values in the attribute with enum variants, e.g. `Iex::ArgExc[ARGUMENT_INVALID]` which could be built into an error enum for a nicer API.

Of course functions that already return a value will need to transformed so that the existing return becomes an out parameter.

**Comment by luke-titley** [comment]
A couple of ideas to add.

```void Foo::foo(int a, int b) CPPMM_THROWS(0, Iex::ArgExc)
                                                CPPMM_THROWS(1, Iex::LogicExc)
                                                CPPMM_THROWS(2, Iex::BaseExc)
                                                CPPMM_THROWS(3, std::exception)
```

Can have multiple attributes.

_Of course functions that already return a value will need to transformed so that the existing return becomes an out parameter._

We could also return a struct which contains the status and the result and rely on a get_error_msg function to get the string.
```
const char * Foo::foo(int a, int b) CPPMM_THROWS(Iex::ArgExc[1] Iex::LogicExc[2] Iex::BaseExc[3] std::exception[4]) 
// becomes:
threadlocal std::string cppmm_tl_exc_what;

typedef struct { const char * result; int status_code; }  Foo_foo_Result;
Foo_foo_Result Foo_foo(int a, int b);
```

That's purely aesthetic though.. and perhaps overkill for a c api whose focus is to be wrapped.

**Comment by anderslanglands** [comment]
Feels like creating a custom type for each function's return might lead to a bit of a code explosion in a library that made heavy use of exceptions (are there any?), and could get very ugly with long namespaces and type names. OTOH it is nice that at least the parameters to the function remain consistent, rather than randomly tacking an extra out parameter on the end when the library decides to throw. I'm leaning towards the out parameters still, but don't feel that strongly about it so fine with whatever you prefer since it falls under asttoc. I will change the separator to a '|' though.

You're right though we want a get_error_msg() function for getting e.what() either way.

**Comment by anderslanglands** [comment]
I do kinda like the idea of doing:
```c++
float Foo::foo(int a) 
    CPPMM_THROWS(Iex::ArgExc, IEX_INVALID_ARGUMENT)
    CPPMM_THROWS(Iex::LogicExc, IEX_LOGICAL_ERROR)
    CPPMM_THROWS(std::exception, IEX_UNKNOWN_ERROR);
```
and having asttoc generate something like:
```c++
threadlocal std::string cppmm_tl_exc_what;

const char* cppmm_get_error_string() {
    return cppmm_tl_exc_what.c_str();
}

enum IexErrorEnum {
    IEX_SUCCESS = 0,
    IEX_INVALID_ARGUMENT = 1,
    IEX_LOGICAL_ERROR,
    IEX_UNKNOWN_ERROR
};

int Foo_foo(int a, float* result) {
    try {
        *result = Foo::foo(a);
        return IEX_SUCCESS;
    } except (Iex::ArgExc& e) {
        cppmm_tl_exc_what = e.what();
        return IEX_INVALID_ARGUMENT;
    } except (Iex::LogicExc& e) {
        cppmm_tl_exc_what = e.what();
        return IEX_LOGICAL_ERROR;
     } except (std::exception& e) {
        cppmm_tl_exc_what = e.what();
        return IEX_UNKNOWN_ERROR;
    }
}
```

**Comment by anderslanglands** [comment]
Thinking about this more, I think we kinda need to handle the possibility of `std::exception` being thrown on *every* function that's not marked `nothrow`, which for OpenEXR is all of them unfortunately. We could add another attribute CPPMM_NOTHROW to add this info where the library itself doesn't bother. From what I remember OIIO and OSL are much better about this. Not sure about USD.

**Comment by anderslanglands** [comment]
I've started thinking about this again as we get closer to getting OpenEXR built. I'm now leaning towards transforming *every* function to return an exception code, and putting the regular return value either as an out parameter either as the first or last parameter. If the function is marked noexcept, it would still be transformed, but will always return SUCCESS. 

The advantage of this is that it's consistent - as a user you always know that you're expecting a status code in the return value, you don't have to check the docs every time. This is the approach that CUDA takes and I quite like it there. 

Another advantage is that the API doesn't have to change if we change the noexcept status of a function. In order to be correct, where a function is not marked noexcept explicitly, we need to be defensive and assume it can throw. Figuring out whether we can make it "nothrow" on our side is an optimization (since we don't need to create the try/catch machinery in the wrapper function), but requires closely inspecting the library code to figure out if it's safe. If we apply a signiature transformation only when the function is no noexcept, then we'd need to make a  breaking API change any time we applied this optimization.

The disadvantage is that it's a little more verbose on the client side:
```c++
int thing = get_thing();

// becomes
int thing;
Exc ignored = get_thing(&thing);
```

Of course on the Rust side this means every function returning a Result in the -sys crate. In most cases it will be fine to call `unwrap()/expect()` if an unexpected exception got caught, and then the -rs crate doesn't need to worry about any of this.

Assuming we do want to go with the "always transform" approach, them the remaining question is do we want to put the original return value as the first or last parameter?
```c++
float p0, p1;
int result = maybe_throws(p0, p1);

// becomes
Exc err = maybe_throws(&result, p0, p1);
// or 
Exc err = maybe_throws(p0, p1, &result);
```

**Comment by luke-titley** [comment]
I'm in favour of always returning an error state in the c api.
* Its consistent like you say.
* It can be ignored if you're testing things in c.
* I suspect it might simplify asttoc.

I'm keen to do this now, albeit just the signature change, and worry about the code to catch the errors a bit later on.

**Comment by luke-titley** [comment]
About whether the return value should be the first or last parameter. My gut says the first, but I can't think of any concrete argument in favour of either.

**Comment by anderslanglands** [comment]
Yeah I don't have a strong feeling either way so first seems fine to me!

**Comment by anderslanglands** [comment]
With 3550cf41 this should be complete now
