### ISSUE TITLE
Enforce Rust style on generation

### ISSUE THREAD

**Issue by anderslanglands** [vfx-rs/cppmm#44]
Potentially contentious idea here... I think we should apply Rust's style rules to the C API so that the API is consistent across all crates from C to -sys to -rs. By this I mean transforming ugly camelCase identifiers to beautiful snake_case. I think 99% of record names are PascalCase already, but enum variants might need looking at too.

**Comment by scott-wilson** [comment]
Hmm...

On the surface, I have no issue with this. But, if we want to have the wrapped projects use our C bindings as the official bindings, chances are they'd probably have the final say. So, I think that it makes sense to say let's try to make sure the C style matches the C++ style as much as possible. I think we have a bit of leniency with the Rust API, though.

**Comment by anderslanglands** [comment]
Thing is, it has to happen somewhere - they final -rs crate needs to be in Rust style. So we either do it in the C API or in the -sys crate. If we do it in the -sys crate then we can't use types and enums from -sys directly, but have to convert them at the -rs/-sys boundary, which is horrible.

**Comment by scott-wilson** [comment]
That's understandable. I'm personally okay with it being renamed in the C
level, but I guess it depends on if we want to hand the C interface to the
wrapped project. If we do, and they want camel case, then that puts us into
a fun situation.

**Comment by anderslanglands** [comment]
This is just being done at the rust-sys level now where necessary.
