### ISSUE TITLE
Support for enums

### ISSUE THREAD

**Issue by luke-titley** [vfx-rs/cppmm#45]
This issue is for bringing enums online.
If we make sure the c enum is the same size as the underlying type in cpp then we'll be able to return direct references to the cpp enum.
Enums in C are not scoped, so we'll also need to add a namespace prefix to the enum variants.

**Comment by luke-titley** [comment]
Okay so this issue is more complex that I anticipated.

Enums in c++ can have an underlying type, that is the developer can specify char/short/int/long int for how large the enum will be in memory. C doesn't allow this, the compiler picks a size based on the contents of the enum, on my platform it's int32. What this means is, there is no one for one memory layout for cpp enum to c enum.

My solution is to use the underlying type as the C type for the enum. So if the underlying type in c++ is char, the enum type in C would be a typedef to a char. I keep around the enum variants in a c enum of the same name as the typedef but with the _e suffix, given that in C enum variants have global scope I don't imagine anyone referring to the _e name directly. Additionally, given that C enums implicitly convert to and from integer types it will still be easy to pass an enum choice onto a c function that accepts the enum type.

Doing this gives me a one for one mapping, which means I can cast directly from the C enum value/pointer to the C++ and vis-versa. The primary benefit of this is when an enum value is returned by reference, if you can't do a direct cast from the c++ type to the c type, then you have to create a new enum which means re-working the function parameters to take a reference to that new value.

The cost of this is type safety in the C api, you could pass the wrong enum type into a function and the compiler would not complain.

An alternative solution might be to declare the enum type in the C api as a struct, with generated functions you have to use to set it's value, for me that seems a bit too heavy handed.

So the question is:
are we willing to sacrifice the type safety and go with the initial solution I propose?
if not,
can anyone think of a better solution?

**Comment by anderslanglands** [comment]
If it was me I’d probably just hard-cast everything to an int so I think
your proposed solution is much better :)

**Comment by luke-titley** [comment]
that's a relief. That means I can finish enums this week.
