### ISSUE TITLE
std::vector<std::string> parameter does not map to bound std_vector type.

### ISSUE THREAD

**Issue by luke-titley** [vfx-rs/cppmm#65]
To reproduce:
* checkout [stdstring-in-openexr](https://github.com/vfx-rs/cppmm/tree/stdstring-in-openexr) branch
* build and run bash bind.sh in root
* Notice in the output that the follow method is skipped 'Imf_2_5::defaultViewName' and that it is because a type hasn't been found for ```std::vector<std::string>```
* Notice that 'test/openexr/bind/std_vector.cpp' contains a definition for ```std::vector<std::string>```
* Look at the ast output for defaultViewName, in test/openexr/ref/ast/imf_multiview.json.
```json
{
            "kind": "Function",
            "id": 2948,
            "short_name": "defaultViewName",
            "qualified_name": "Imf_2_5::defaultViewName",
            "in_binding": false,
            "in_library": false,
            "attributes": null,
            "namespaces": [
                3
            ],
            "return": {
                "kind": "RecordType",
                "id": 241,
                "type": "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >",
                "record": 1847,
                "const": false
            },
            "params": [
                {
                    "index": 0,
                    "name": "multiView",
                    "type": {
                        "kind": "Reference",
                        "id": 2221,
                        "type": "const class std::__1::vector<class std::__1::basic_string<char, struct std::__1::char_traits<char>, class std::__1::allocator<char> >, class std::__1::allocator<class std::__1::basic_string<char, struct std::__1::char_traits<char>, class std::__1::allocator<char> > > > &",
                        "pointee": {
                            "kind": "RecordType",
                            "id": 2220,
                            "type": "std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >",
                            "record": -1,
                            "const": true
                        },
                        "const": false
                    },
                    "attrs": []
                }
            ]
        },
```

* Notice the -1 in the 'record' field of the multiview parameter. This should not be -1 it should be 1541 which is the id of the std::__1::vector<std::string> type.

**Comment by anderslanglands** [comment]
Yeah this is a consequence of clang not generating reliable names for things. Which is a massive PITA. I thought I'd got this working reliably, but of course I was wrong. This might take some time and a lot of noodling to fix.

**Comment by anderslanglands** [comment]
I have a horrible feeling we're going to need to manually expand the name by recursively expanding all namespaces and template parameters.

**Comment by anderslanglands** [comment]
Actually it gets worse. The expanded names will be different for each libstdc++ implementation, and those type names will be baked into the ABI, which means the rust-sys crates will be platform-dependent. 

I’m starting to think we need to handle std:: types specially. In other words heuristically figure out that the types we’re dealing with are “vector” and “string” etc and give them sensible names

**Comment by luke-titley** [comment]
>I’m starting to think we need to handle std:: types specially. In other words heuristically figure out that the types we’re dealing with are “vector” and “string” etc and give them sensible names

ouf, I was hoping it was just an issue with the way I wrote the bind file. I'm fine with us special casing stl types.

**Comment by anderslanglands** [comment]
After some investigation I think clang's name mangling can help us here as it seems to generate a unique, matching identifier in both places, so that will probably solve the first issue. It's a little bit of invasive surgery but not too bad in the grand scheme of things I hope.

We'll still need some way of "winding up" the std types to be platform agnostic, which I think should just be a case of handling the versioned namespace under `std::`. This is either  `std::__cxx11` or `std::` for libstdc++ depending on flags and the particular type (sigh), or `std::__1` for libc++ . No idea what it is for MSCV. 

Just so we're on the same page, the issue is:
```c++
// this declaration in c++
std::vector<std::string>;

// is really something like...
std::__1::vector<std::__1::string>;    //< clang
std::vector<std::__cxx11::string>;     //< gcc

// so our C structs would be
typedef struct {/*...*/} std____1__vector_std____1__string_;    //< clang
typedef struct {/*...*/} std__vector_std____cxx11__string_;     //< gcc
```

We need to handle versioned child namespaces anyway (ptex uses this method as opposed to baking it into the main namespace), so I *think, maybe* we can just do something as part of a solution to that, by allowing to collapse namespaces in the qualified name as well as the nice name. Not sure how we'd specify that right now. Needs some more thought.

**Comment by luke-titley** [comment]
okay well I see this as being three separate issues (though in the same sort of area).
* This issue, with names not matching when they should, hopefully solved using clang name mangling solution you mentioned yesterday.
* Issue with libc++/libstdc++ namespace differences.
* Issue with namespace renaming/simplification across libs (https://github.com/vfx-rs/cppmm/issues/63)

is it possible to solve this issue (first) without trying to solve the other two, just for the short term?
I think we could do with an issue just for stl types to make a strategy for them in general:
* remove the version child namespace
* heap allocate them etc
