### ISSUE TITLE
naming and calling template instantiations

### ISSUE THREAD

**Issue by anderslanglands** [vfx-rs/cppmm#79]
Slight issue when dealing with template methods. For instance in openexr:
```c++
struct Header {
    template <class T>
    T* findTypedAttribute(const char name[])
        CPPMM_THROWS(Iex::ArgExc, IEX_INVALID_ARGUMENT);
    template <class T>
    const T* findTypedAttribute(const char name[]) const
        CPPMM_RENAME(findTypedAttribute_const)
            CPPMM_THROWS(Iex::ArgExc, IEX_INVALID_ARGUMENT);
};
```
astgen doesn't currently have a way of associating the explicit instantiations of a method with a nice name. I assume there's a way of matching against the instantiation decl but needs looking into. More than that, we also need to change how these functions are called in the wrapper, as they will need to specify the template arguments explicitly, e.g. `findTypedAttribute<IntAttribute>("my_int_attr")`, which means passing them through from astgen as well...

**Comment by luke-titley** [comment]
ouf, okay. They need some sort of explicit instantiation with a rename..

**Comment by anderslanglands** [comment]
Added a PR that addresses this: https://github.com/vfx-rs/cppmm/pull/80

I'd appreciate you taking a look over it if you get time - starting to get my head around the asttoc structure but want to make sure I haven't done anything too horrible.
